name: Deploy Azure VM with Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set Azure Environment Variables
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      run: |
        echo "Setting Azure environment variables..."
        echo "ARM_SUBSCRIPTION_ID=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r '.subscriptionId')" >> $GITHUB_ENV
        echo "ARM_CLIENT_ID=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r '.clientId')" >> $GITHUB_ENV
        echo "ARM_CLIENT_SECRET=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r '.clientSecret')" >> $GITHUB_ENV
        echo "ARM_TENANT_ID=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r '.tenantId')" >> $GITHUB_ENV

    - name: Initialize Terraform
      run: terraform init

    - name: Import existing resource group
      run: terraform import azurerm_resource_group.rg /subscriptions/71746fc8-d31b-44dd-8ff5-7b8f5cd8b9e2/resourceGroups/my-terraform-rg || true
      run: terraform import azurerm_virtual_network.vnet /subscriptions/71746fc8-d31b-44dd-8ff5-7b8f5cd8b9e2/resourceGroups/my-terraform-rg/providers/Microsoft.Network/virtualNetworks/my-terraform-rg-vnet


    - name: Plan Terraform deployment
      run: terraform plan -out tfplan

    - name: Apply Terraform deployment
      run: terraform apply -auto-approve tfplan
