name: Deploy Azure VM with Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6

    - name: Login to Azure
      id: azure_login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set Azure Environment Variables
      run: |
        echo "Extracting credentials..."
        export ARM_SUBSCRIPTION_ID=$(echo "${{ secrets.AZURE_CREDENTIALS }}" | jq -r .subscriptionId)
        export ARM_CLIENT_ID=$(echo "${{ secrets.AZURE_CREDENTIALS }}" | jq -r .clientId)
        export ARM_CLIENT_SECRET=$(echo "${{ secrets.AZURE_CREDENTIALS }}" | jq -r .clientSecret)
        export ARM_TENANT_ID=$(echo "${{ secrets.AZURE_CREDENTIALS }}" | jq -r .tenantId)
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Initialize Terraform
      run: terraform init

    - name: Plan Terraform deployment
      run: terraform plan -out tfplan
      env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_CREDENTIALS.subscriptionId }}
        ARM_CLIENT_ID: ${{ secrets.AZURE_CREDENTIALS.clientId }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CREDENTIALS.clientSecret }}
        ARM_TENANT_ID: ${{ secrets.AZURE_CREDENTIALS.tenantId }}

    - name: Apply Terraform deployment
      run: terraform apply -auto-approve tfplan
      env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_CREDENTIALS.subscriptionId }}
        ARM_CLIENT_ID: ${{ secrets.AZURE_CREDENTIALS.clientId }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CREDENTIALS.clientSecret }}
        ARM_TENANT_ID: ${{ secrets.AZURE_CREDENTIALS.tenantId }}
